# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform:ios,'12.0'

target 'SingularCardApp' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  # Pods for SingularCardApp
end
